### ISSUE TITLE
jshint files?

### ISSUE THREAD

**Issue by smnbbrv** [jmandzik/postmerge-npm-install#1]
Hi there,

is the project alive? I really like the approach, but what I don't get how is it connected to these .jshintrc etc files?

Is there any way to avoid creating them?

**Comment by jmandzik** [comment]
Hey @smnbbrv, this was just a quick thing throw together a while back to meet a specific projects need.  Its not maintained at all, so feel free to fork/steal anything that's useful.  The core usefulness of it was to drop the post merge hook in the right directory; the JSHint stuff can all be ripped out.

**Comment by smnbbrv** [comment]
Hi @jmandzik, thank you for clarifying 👍
